nanme: document
services:
  document:
    image: ghcr.io/ranui/document:latest
    container_name: document
    ports:
      - 8080:80
    # 进阶配置
    # volumes:
    #   # 证书
    #   - 证书路径:/ssl
    # environment:
    #   # 账号
    #   # 格式用户名:密码，必须使用BCrypt密码哈希函数对密码进行编码。
    #   # 获取BCrypt加密的结果，把加密结果中的$替换成$$转义。
    #   SERVER_BASIC_AUTH: "用户名:BCrypt加密密码"
    #   # 证书
    #   SERVER_HTTP2_TLS: true
    #   SERVER_HTTP2_TLS_CERT: 证书路径
    #   SERVER_HTTP2_TLS_KEY: 私钥路径
